node:
  - lib/msal-node/**/*
angular:
  - lib/msal-angular/**/*
msal@1.x:
  - lib/msal-core/**/*
msal-common:
  - lib/msal-common/**/*
msal-browser:
  - lib/msal-browser/**/*
samples:
  - samples/**/*
