# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run CI (Build and Test)

on:
  push:
    branches:
      - 'dev'
      - 'master'
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          library:
            - msal-core
            - msal-angular
            - msal-common
            - msal-browser
            - msal-node
  
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Build packages
      working-directory: lib/${{ matrix.library }}
      run: npm run build:all

    - name: Lint
      working-directory: lib/${{ matrix.library }}
      run: npm run lint

    - name: Unit Tests
      working-directory: lib/${{ matrix.library }}
      run: npm run test:coverage
