# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run CI (Build and Test)

on:
  push:
    branches:
      - 'dev'
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      NOT_FROM_FORK: ${{ (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push')) }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Build packages
      run: npm run build

    - name: Lint
      run: npm run lint

    - name: Unit Tests
      run: |
        npm run test:coverage
        npm run test:report

    - name: Coveralls
      if: success() && env.NOT_FROM_FORK == 'true'
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          