# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: electron E2E Tests

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    paths:
      - 'lib/msal-node/**/*'
      - 'lib/msal-common/**/*'
      - 'samples/msal-node-samples/**/*'
      - 'samples/e2eTestUtils/**/*'
      - 'samples/package-lock.json'
      - '!**.md'
      - '.github/workflows/electron-e2e.yml'

concurrency:
  group: electron-e2e-${{github.ref}}
  cancel-in-progress: true

jobs:
  run-e2e:
    if: (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && (github.actor != 'dependabot[bot]') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        sample:
          - 'ElectronTestApp'

    name: ${{ matrix.sample }} - OS ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Build Package
      working-directory: samples/msal-node-samples
      run: npm run build:package

    - name: Install Test Tools
      working-directory: samples
      run: npm ci

    - name: Install Sample
      working-directory: samples/msal-node-samples/${{ matrix.sample }}
      run: |
        npm run install:local
        npm install
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

    - name: Install Playwright
      working-directory: samples/msal-node-samples/${{ matrix.sample }}
      run: |
        npx playwright install --with-deps chromium

    - name: Build Sample
      working-directory: samples/msal-node-samples/${{ matrix.sample }}
      run: |
        npm run build

    - name: E2E Tests
      if: matrix.os != 'ubuntu-latest'
      working-directory: samples/msal-node-samples/${{ matrix.sample }}
      timeout-minutes: 10
      env:
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      run: npm test

    - name: E2E Tests
      if: matrix.os == 'ubuntu-latest'
      working-directory: samples/msal-node-samples/${{ matrix.sample }}
      timeout-minutes: 10
      env:
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm test

    - name: Upload E2E Test Screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: e2e-test-screenshots
        path: samples/**/screenshots
