name: Issue Template Bot

on:
  issues:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Bot
        uses: ./.github/actions/issue_template_bot
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_label_config_path: "./.github/issue_labeler.json"