# NPM Publish is the name for this action
name: NPM Publish

# This action will trigger when Release PR from release-staging branch is merged into dev
on:
  pull_request:
    types: [closed]
    branches:
      - dev

# Job will run on a ubuntu instance
jobs:
  build:
    if: (github.event.pull_request.merged == true && github.head_ref == 'release-staging')
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      # Checkout the code
      - uses: actions/checkout@v2
        # Setup node with version 12.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      #- name: Set npm auth token
      #  run: npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"

      - name: Publish  msal-core
        working-directory: lib/msal-core
        env:
          CDN_EUNO_SAS: ${{ secrets.CDN_EUNO_SAS}}
          CDN_USWE_SAS: ${{ secrets.CDN_USWE_SAS}}
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
          npm install
          npm run build
          npm run cdn:sri
          npm publish
          rm .npmrc

      - name: Publish  msal-common
        working-directory: lib/msal-common
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
          npm install
          npm publish
          rm .npmrc

      - name: Publish  msal-browser
        working-directory: lib/msal-browser
        env:
          CDN_EUNO_SAS: ${{ secrets.CDN_EUNO_SAS}}
          CDN_USWE_SAS: ${{ secrets.CDN_USWE_SAS}}
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
          npm install
          npm run cdn
          npm publish
          rm .npmrc

      - name: Publish  msal-node
        working-directory: lib/msal-node
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
          npm install
          npm publish
          rm .npmrc

      - name: Publish  msal-angular
        working-directory: lib/msal-angular
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
          npm install
          npm run deploy
          rm .npmrc

      - name: Publish  msal-react
        working-directory: lib/msal-react
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
          npm install
          npm publish
          rm .npmrc

      - name: Publish node-extensions
        working-directory: extensions/msal-node-extensions
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
          npm install
          npm publish
          rm .npmrc

      - name: Create Github Releases and Discussions
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN}}
        run: npm run beachball:release

      - name: Update package-locks
        run: npm install

      - name: Get release date
        id: release-date
        run: echo "::set-output name=date::$(node release-scripts/getReleaseDate.js)"

      - name: Get branch
        id: get-branch
        uses: actions/github-script@0.9.0
        with:
          script: |
            const branch = ${{ steps.release-date.outputs.date }}.toLowerCase().replace(/\s+/g, '-')
            core.setOutput('branch', branch)

      # Create Pull Request from post-release-month-year to dev
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Post-release
          branch: post-release-${{steps.get-branch.outputs.branch}}
          title: "${{ steps.release-date.outputs.date }} Post Release"
          body: |
            This PR contains package lock updates & cdn README updates for msal-browser and msal-core.
          draft: false
